### ISSUE TITLE
SMUI tags not working

### ISSUE THREAD

**Issue by raniadhahbi** [querqy/smui#151]
Hello, I need to activate SMUI tags and in order to I  set the key **toggle.rule-tagging=true** in the file application.conf basing on the documentation https://querqy.org/docs/smui/config.html#smui-config-features.
I tried to use the predefined tags but it's not working.
please note that I'm using a database for rules not a file.txt

Can anyone help me with this, please ?  Thank you !

**Comment by mkr** [comment]
Discussion continued in #154.
