### ISSUE TITLE
First start:  Database 'default' is in an inconsistent state!

### ISSUE THREAD

**Issue by hheexx** [querqy/smui#35]
Hi,

I am trying to start smui for the first time.
I  pulled latest container from docker  and I also pulled latest MySQL 8.0.19.
I initialized database by executing 3 sql rows from readme file.

I tried to start smui with this line:

`docker run -p 9000:9000 --network smui -e SMUI_DB_URL="jdbc:mysql://smui-mysql/smui?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true" -v /tmp/smui_deployment_path:/home/hex/solr-8.4.1/server/solr/bmaxpoc/conf pbartusch/smui`

I  receive following exception:

> [info] p.a.d.DefaultDBApi - Database [default] initialized at jdbc:mysql://smui-mysql/smui?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
> [info] application - Creating Pool for datasource 'default'
> [info] c.z.h.HikariDataSource - HikariPool-1 - Starting...
> [info] c.z.h.HikariDataSource - HikariPool-1 - Start completed.
> [info] a.e.s.Slf4jLogger - Slf4jLogger started
> [error] p.a.d.e.DefaultEvolutionsApi - Specified key was too long; max key length is 3072 bytes [ERROR:1071, SQLSTATE:42000]
> Oops, cannot start the server.
> @7fb8ak588: Database 'default' is in an inconsistent state![An evolution has not been applied properly. Please check the problem and resolve it manually before marking it as resolved.]
>         at play.api.db.evolutions.DatabaseEvolutions.$anonfun$checkEvolutionsState$3(EvolutionsApi.scala:309)
>         at play.api.db.evolutions.DatabaseEvolutions.$anonfun$checkEvolutionsState$3$adapted(EvolutionsApi.scala:294)
>         at play.api.db.evolutions.DatabaseEvolutions.executeQuery(EvolutionsApi.scala:341)
>         at play.api.db.evolutions.DatabaseEvolutions.checkEvolutionsState(EvolutionsApi.scala:294)
>         at play.api.db.evolutions.DatabaseEvolutions.evolve(EvolutionsApi.scala:263)
>         at play.api.db.evolutions.DefaultEvolutionsApi.evolve(EvolutionsApi.scala:104)
>         at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$2(ApplicationEvolutions.scala:80)
>         at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$2$adapted(ApplicationEvolutions.scala:68)
>         at play.api.db.evolutions.ApplicationEvolutions$.$anonfun$runEvolutions$1(ApplicationEvolutions.scala:211)
>         at play.api.db.evolutions.ApplicationEvolutions$.withLock(ApplicationEvolutions.scala:232)
>         at play.api.db.evolutions.ApplicationEvolutions$.runEvolutions(ApplicationEvolutions.scala:202)
>         at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$1(ApplicationEvolutions.scala:68)
>         at play.api.db.evolutions.ApplicationEvolutions.$anonfun$start$1$adapted(ApplicationEvolutions.scala:63)
>         at scala.collection.immutable.List.foreach(List.scala:389)
>         at play.api.db.evolutions.ApplicationEvolutions.start(ApplicationEvolutions.scala:63)
>         at play.api.db.evolutions.ApplicationEvolutions.<init>(ApplicationEvolutions.scala:109)
>         at play.api.db.evolutions.ApplicationEvolutionsProvider.get$lzycompute(EvolutionsModule.scala:68)
>         at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:61)
>         at play.api.db.evolutions.ApplicationEvolutionsProvider.get(EvolutionsModule.scala:51)
>         at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:85)
>         at com.google.inject.internal.BoundProviderFactory.provision(BoundProviderFactory.java:77)
>         at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:59)
>         at com.google.inject.internal.BoundProviderFactory.get(BoundProviderFactory.java:61)
>         at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
>         at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
>         at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
>         at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:211)
>         at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:182)
>         at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
>         at com.google.inject.Guice.createInjector(Guice.java:87)
>         at com.google.inject.Guice.createInjector(Guice.java:78)
>         at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:201)
>         at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:156)
>         at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:22)
>         at play.core.server.ProdServerStart$.start(ProdServerStart.scala:59)
>         at play.core.server.ProdServerStart$.main(ProdServerStart.scala:31)

**Comment by pbartusch** [comment]
hi @hheexx , from what I am reading this problem seems to originate between the way the database connection is configured (with `allowPublicKeyRetrieval`) and the `JDBC driver`. I think the important part of the error lies in `Specified key was too long; max key length is 3072 bytes [ERROR:1071, SQLSTATE:42000]` (the inconsistent state seems to be the consequence).

So far they weren't any scenarios with SMUI and a database exchanging a public key ... very interesting use case.

Have you managed to start SMUI without the public key exchange in order to track down the source of error?

**Comment by hheexx** [comment]
Hi  @pbartusch,

First I received exception like in this thread:
https://stackoverflow.com/questions/50379839/connection-java-mysql-public-key-retrieval-is-not-allowed

I added allowPublicKeyRetriveal=true from answer there.

**Comment by epugh** [comment]
Hi @pbartusch I don't think the public key is the issue.  I found that this line wouldn't run:

https://github.com/pbartusch/smui/blob/master/conf/evolutions/default/3.sql#L20

And I think it's because one of the fields that is to be in the index is 1000 characters long???

If I drop that one line, then things work.

**Comment by epugh** [comment]
Just retested, and I see in my `play_evolutions` table the string: 
```
Specified key was too long; max key length is 767 bytes [ERROR:1071, SQLSTATE:42000]
```

Loading the script with out the line, and marking id=3 as being "applied" and then restarting SMUI and it works!

**Comment by pbartusch** [comment]
Thanks @epugh for the hint here. That seems plausible. This issue seems to be new with the MySQL version 8. Other versions or SMUI supported databases have worked so far with, maybe that constraint can be fixed (I found the following link https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes)

But for future release, I will consider to reduce the key size for the table @epugh you pointed out.

@hheexx : Do you depend on a MySQL v8 or would it be possible for you to use e.g. Postgres instead?

**Comment by epugh** [comment]
I wonder, to reduce the support burden, if you should just pick a specific database to work with SMUI?  I am running SMUI in a Docker Compose setup (as soon as I get it all working!), so which database doesnt' matter to me.  I saw this issue with Mysql 5.6.37.  Is there a version you recommend I use?

```
smui_db:
    container_name: smui_db
    image: mysql:5.6.37
```

**Comment by epugh** [comment]
Okay, I moved to `image: mysql:5.7.29` after reading your link, and problem went away.  

Might be useful to the community to have a good demo set up that has SMUI, Solr, and Querqy ;-)

**Comment by hheexx** [comment]
I  switched to postgres and now it works.

Also it would be nice if you could add to readme nice short quick startup script like this:

1) docker run --network smui --name smui-postgres -e POSTGRES_PASSWORD=<password> -d postgres

2) SQL : CREATE USER smui WITH PASSWORD 'smui'; CREATE DATABASE smui;

3) docker run -p 9000:9000 --network smui -e SMUI_DB_URL="jdbc:postgresql://smui-mysql/smui?autoReconnect=true&useSSL=false" -v /tmp/smui_deployment_path:/path/to/solr/core/conf pbartusch/smui

**Comment by pbartusch** [comment]
hi @hheexx , good to hear. I will add MySQL ver > 8 support on the list of feature requests for SMUI. If you have further questions or encounter other situations while using SMUI , let me know!

furthermore , I plan for making the SMUI bootstrap documentation more straight forward and maybe add a docker-compose like @epugh suggested as well.

**Comment by hheexx** [comment]
That would be great!

I have started application now but I can't publish rules.txt anywhere.It's not even in temp dir.
Mu solr list in top-right is  empty:
![image](https://user-images.githubusercontent.com/103767/78938941-7510ee80-7ab3-11ea-82cf-4572e7b30fb1.png)

Console text:
In AppComponent :: handleError app.component.ts:95:12
:: error = TypeError: _this.listSolrIndeces[0] is undefined


Unrelated notices:
- Your angular is in dev mode: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
-  Angular is old
-  You should bundle frontend code.


I am good Angular developer and I'm willing to contribute if I find this project useful for my use case.

**Comment by epugh** [comment]
@hheexx we may be fighting the same issue.  See #39  for proposed fix.

**Comment by epugh** [comment]
It this still a valid issue?  I haven't run into it in a while.

**Comment by pbartusch** [comment]
yes , seems old and not reoccured (at least , I havent heard anything). @hheexx , I will close that issue. If you encounter the problem again , let me know.

**Comment by hheexx** [comment]
Ok.
I couldn't make smui work for me so I abandon it.
Maybe I try again in the future...

**Comment by epugh** [comment]
Take a look at a related project, http://github.com/querqy/chorus that walks you through the full setup of SMUI, and may point you in the right direction!

**Comment by hheexx** [comment]
Thanks! I was not aware of chorus.
It's definitely something I need.

I will consider it when time comes and maybe contribute...
