### ISSUE TITLE
It shouldn't possible to save empty filter rules

### ISSUE THREAD

**Issue by ChristianSchaefer** [querqy/smui#51]
Hi,

we had the problem, that it is possible to save empty filter rules, which leads to a syntax error, when deploying into solr.
Here is an excerpt of our rules-smt file

> DOWN(50): * manufacturer:Wiko
DOWN(50): * manufacturer:ZTE
DOWN(10): * searchText:"Iphone 11"
FILTER: * -searchText:
FILTER: * -searchText:"Mi Smart Plug"
FILTER: * -searchText:"Roboter-Staubsauger"

**Comment by pbartusch** [comment]
hi @ChristianSchaefer ,

I understand, you are referring to the rule:

> FILTER: * -searchText:

presumably you'd like to express a rule, that states:

"For the managed query, the (Solr) field searchText should not be searches at all"

Is that correct?

The following rule definition will be positively validated by Querqy:

> FILTER: * -searchText: *

Although I am not sure, what will be the specified outcome of that in Querqy ( @renekrie ?), and if there is even a way to use Querqy's CommonRuleRewriter in a way, that it prevents complete fields from being searched by Solr/Lucene.

Very interesting case though!! @ChristianSchaefer , it would be great to learn more about your use case intent , and wether above's suggestion works for you!?

**Comment by renekrie** [comment]
`FILTER: * -searchText:` is indeed invalid Solr/Lucene syntax.

@pbartusch I think your solution `FILTER: * -searchText:*` could work (I'd remove the space after the colon though).

I think @ChristianSchaefer's point is that it shouldn't be possible to save such a rule in SMUI.  Overall, whatever you put in that query string is completely transparent to Querqy - it will just ask Solr to parse the query at runtime. Unfortunately, we cannot validate Lucene/Syntax 100% outside Solr. For example, the query string might use plugged in custom query parsers that we don't know about in SMUI. Also, we cannot validate that a field exists. Strictly spoken, in some cases we might not even know that a given piece of the string refers to a field. 

However, we should make sure that this is not a rule that was produced by SMUI, for example, when the user entered a field name in the UI without specifying any field value.

**Comment by ChristianSchaefer** [comment]
@renekrie is right. It shouldn't be possible to save empty rules or a warning should appear, if this is a desired feature. If you save an empty rule with *, the result of the query isn't predictable, right?

**Comment by pbartusch** [comment]
thanks @ChristianSchaefer for the report. I released v3.11.11 , that should solve the issue.
