### ISSUE TITLE
Admin Screen to Manage Rules Collections

### ISSUE THREAD

**Issue by epugh** [querqy/smui#64]
Today, we have to use a API call to create a Solr Index in SMUI:

```
SOLR_INDEX_ID=`curl -S -X PUT -H "Content-Type: application/json" -d '{"name":"ecommerce", "description":"Ecommerce Demo"}' http://localhost:9000/api/v1/solr-index | jq -r .returnId`
```

I am working with a client that, if we are successful, will have many collections.    They could use this API call, however it would be nice if SMUI had an admin interface that let you via clicking create and update new "Solr Index".   Bonus points on if you could edit the deployment scripts via the web interface ;-)

**Comment by renekrie** [comment]
It sounds great, but let's keep in mind that it should also work for ES some day, and Solr access is not always as simple as an HTTP call --> we'll need good abstractions

**Comment by pbartusch** [comment]
The internal concept `SolrIndex` is deprecated. We already started to refactor it to the concept of a `Deployment Channel` in the documentation. The corresponding code refactoring should be part of that issue, when establishing an admin interface for the channels. The concept is decoupled from a specific search engine as it will only be used to organise rules.

Note: when refactoring the `SolrIndex` also the database structure needs to be touched.

**Comment by pbartusch** [comment]
Reminder: When establishing an admin interface to manage the Deployment Channels, it should also be considered to establish an admin interface for managing the Rule Tags (currently configured via an explicit file referred by the `application.conf`).

**Comment by pbartusch** [comment]
linked also to #65
