### ISSUE TITLE
SMUI 3.13.0 -> "publish to LIVE" confirmation box does not go away after clicking 'Yes'

### ISSUE THREAD

**Issue by jaceq** [querqy/smui#87]
As per title, I have deployed smui 3.13.0 and no confirmation box (as per picture) does not go away after clicking 'Yes' (it does however after clicking no). 
Process on the background does work, after a bit I get a green confirmation on bottom of the page (as per picture). 

![image](https://user-images.githubusercontent.com/12188427/143861168-c3f8103c-4482-457d-bd29-cc31bfff424b.png)

**Comment by epugh** [comment]
I just duplicated this as well...    Are you interested in submitting a PR for this?

**Comment by epugh** [comment]
It ended up being easy to fix!

**Comment by jaceq** [comment]
Awesome, I am looking forward to new release without this bug. Thanks!
