### ISSUE TITLE
RFE: Add meta-data to rules

### ISSUE THREAD

**Issue by schnoddelbotz** [querqy/smui#9]
Dropping the idea here as recently discussed:

In our usage scenario, it would be helpful to provide some additional information per rule, e.g.
- A "human-readable" comment on what the rule aims to achieve
- Who (which user) requested or created the rule in SMUI
- Point in time when the rule was created / modified
Further meta-data comes to mind, maybe to limit rules lifetime for specific boosts...?

Opening the ticket here as recently discussed... for further discussion.

**Comment by pbartusch** [comment]
hi @schnoddelbotz , good improvement suggestion. I am going to eval that with next SMUI update / release. thanks!

**Comment by pbartusch** [comment]
There also came up the idea to kind of classify / categorize or group rules of specific type. That could be a specific functional aspect as well as a specific business need (eg "campaign intended rules"). By that, it's also imaginably to deploy specific rules just for specific tenants (within a multi-tenant-setup). Maybe this is a different concert / requirement or it is the same ... I am considering ...

**Comment by schnoddelbotz** [comment]
Just as short follow-up -- We have one more use-case in the meantime:
Automated mass-import/(update)/delete of rules (here: from an Excel-Sheet). We preferred import via API as DB is quite inaccessible/error-prone. For the mass-update-use-case (which means delete all previously imported of same type and do a fresh re-import), this feature would be a big win; currently we have to track generated UIDs. Would be awesome if we could just import with custom meta-data like `usage=customer-xx` and for update purposes, mass-delete based on meta-tag.

Is there a rough plan/ETA for the overall feature ... or could PRs help to get this in?

**Comment by pbartusch** [comment]
hi @schnoddelbotz , this issue is rather old , and in the meantime commenting on rules had been introduced by SMUI. does this solve the purpose. I think rule comments can be considered a META data and should also be definable for rules automatically imported.

**Comment by schnoddelbotz** [comment]
hi @pbartusch . indeed, we're using rule comments to 'tag' rules imported automatically. thanks!
